// Edit this file to update the gallery.
const GH = "https://github.com/stephencox1026";
const PAGES = "https://stephencox1026.github.io";

const PROJECTS = [
  {
    name: "Snowflake Reliability Intelligence",
    bucket: "B · Data Platform / Cortex",
    desc: "Batch Cortex ML + RCA narratives + Analyst Metrics Explorer — Critical/High action queue and Solution playbooks for data-pipeline reliability (not a chatbot).",
    metric: "2/3/2/10 criticality mix · Analyst 10/10 · offline Cortex proxy",
    stack: ["Python", "Snowflake Cortex", "scikit-learn", "Streamlit", "FastAPI"],
    repo: GH + "/snowflake-reliability",
    demo: null,
    featured: true,
  },
  {
    name: "Customer Churn Prediction",
    bucket: "A · Predictive ML",
    desc: "End-to-end churn model on synthetic customer data with retention recommendations — mirrors real retention analytics.",
    metric: "Predict who leaves, then act · XGBoost",
    stack: ["Python", "XGBoost", "scikit-learn", "pandas"],
    repo: GH + "/customer-churn-prediction",
    demo: null,
    featured: true,
  },
  {
    name: "AI Report Agent",
    bucket: "F · Generative AI",
    desc: "Multi-step LLM agent that turns raw data into an executive brief, computing every figure with deterministic tools.",
    metric: "Raw data → executive brief in seconds",
    stack: ["Python", "LLM agent", "Tool calling"],
    repo: GH + "/ai-report-agent",
    demo: null,
    featured: true,
  },
  {
    name: "Agentic RAG Analyst",
    bucket: "F · Generative AI",
    desc: "Retrieval-augmented LLM assistant answering over a private corpus with inline citations + an eval harness.",
    metric: "Cited answers · eval harness (RAGAS)",
    stack: ["Python", "LLM", "Vector DB", "RAGAS"],
    repo: GH + "/agentic-rag-analyst",
    demo: null,
    featured: true,
  },
  {
    name: "Model Serving API",
    bucket: "A · Cloud / Production",
    desc: "Trained model wrapped in a FastAPI service, containerized with Docker for cloud deployment with monitoring.",
    metric: "Live /predict endpoint · Docker · cloud",
    stack: ["Python", "FastAPI", "Docker", "Cloud"],
    repo: GH + "/model-serving-api",
    demo: null,
    featured: true,
  },
  {
    name: "NBA Rebound Prediction",
    bucket: "A · Predictive ML",
    desc: "End-to-end ML system predicting rebounds and flagging positive-EV opportunities (forecasting + decision rule).",
    metric: "MAE ~1.5-2.0 · R² ~0.4-0.6 · 15%+ edge flags",
    stack: ["Python", "XGBoost", "Feature Eng.", "SQLite"],
    repo: GH + "/nba-rebound-prediction",
    demo: null,
  },
  {
    name: "MLB Matchup Modeling",
    bucket: "A · Production ML / MLOps",
    desc: "Fault-tolerant daily prediction pipeline with automated data-quality gates and reproducible runs.",
    metric: "Automated QA · calibration · zero silent drift",
    stack: ["Python", "GBDT", "Statcast", "Automation"],
    repo: GH + "/mlb-matchup-modeling",
    demo: null,
  },
  {
    name: "NFL Home-Underdog ATS",
    bucket: "D · Quant / Financial",
    desc: "11-season strategy backtest quantifying edge, with automated reporting and segmentation.",
    metric: "2014-2024 · automated report + charts",
    stack: ["Python", "pandas", "Backtesting"],
    repo: GH + "/nfl-home-underdog-ats",
    demo: PAGES + "/nfl-home-underdog-ats/outputs/analysis_report.html",
  },
  {
    name: "D1 Recruiting Dashboard",
    bucket: "C · BI / Decision Support",
    desc: "Deployable Streamlit app ranking 95 prospects with a transparent weighted-scoring model.",
    metric: "Weighted scoring · interactive filters",
    stack: ["Python", "Streamlit", "Scoring model"],
    repo: GH + "/d1-baseball-recruiting-dashboard",
    demo: null,
  },
  {
    name: "College Baseball Data Pipeline",
    bucket: "B · Data Engineering",
    desc: "ETL that scrapes multiple sources into a normalized PostgreSQL schema with fuzzy entity matching.",
    metric: "4 conferences · idempotent upserts",
    stack: ["Python", "PostgreSQL", "Scraping", "ETL"],
    repo: GH + "/college-baseball-data-pipeline",
    demo: null,
  },
  {
    name: "Polymarket Arbitrage",
    bucket: "D · Quant / Financial",
    desc: "Interactive tool detecting cross-market pricing inefficiencies and computing expected return.",
    metric: "Live calculator · EV · P&L log",
    stack: ["JavaScript", "Probability", "HTML/CSS"],
    repo: GH + "/polymarket-arbitrage",
    demo: PAGES + "/polymarket-arbitrage/",
  },
  {
    name: "Sports Analytics Studies",
    bucket: "E · Analysis & Reporting",
    desc: "A collection of focused analytics studies (CFP, NFL, MLB) with automated reporting.",
    metric: "Multiple studies · auto reports",
    stack: ["Python", "pandas", "Reporting"],
    repo: GH + "/sports-analytics-studies",
    demo: PAGES + "/sports-analytics-studies/nfl-over-under/dashboard.html",
  },
];
