// Edit this file to update the gallery. Replace [verify] metrics and repo URLs once published.
const GH = "https://github.com/stephencox1026";

const PROJECTS = [
  {
    name: "NBA Rebound Prediction",
    bucket: "A · Predictive ML",
    desc: "End-to-end ML system predicting NBA rebounds and flagging positive-EV opportunities (15%+ edge).",
    metric: "MAE ~1.5-2.0 · R² ~0.4-0.6 · ROI [verify]",
    stack: ["Python", "XGBoost", "Feature Eng.", "SQLite"],
    repo: GH + "/nba-rebound-prediction",
    demo: null,
    featured: true,
  },
  {
    name: "MLB Matchup Modeling",
    bucket: "A · Production ML / MLOps",
    desc: "Fault-tolerant daily prediction pipeline with automated data-quality gates and reproducible runs.",
    metric: "Automated QA · calibration · zero silent drift",
    stack: ["Python", "GBDT", "Statcast", "Automation"],
    repo: GH + "/mlb-matchup-modeling",
    demo: null,
    featured: true,
  },
  {
    name: "NFL Home-Underdog ATS",
    bucket: "D · Quant / Financial",
    desc: "11-season strategy backtest quantifying betting edge, with automated reporting and segmentation.",
    metric: "2014-2024 · ATS cover [verify]% · ROI [verify]%",
    stack: ["Python", "pandas", "Backtesting", "HTML reports"],
    repo: GH + "/nfl-home-underdog-ats",
    demo: null,
    featured: true,
  },
  {
    name: "D1 Recruiting Dashboard",
    bucket: "C · BI / Decision Support",
    desc: "Deployable Streamlit app ranking 95 prospects with a transparent weighted-scoring model.",
    metric: "30 SP / 15 RP / 50 hitters · Power-4",
    stack: ["Python", "Streamlit", "Scoring model"],
    repo: GH + "/d1-baseball-recruiting-dashboard",
    demo: null,
    featured: true,
  },
  {
    name: "College Baseball Data Pipeline",
    bucket: "B · Data Engineering",
    desc: "ETL that scrapes multiple sources into a normalized PostgreSQL schema with fuzzy entity matching.",
    metric: "4 conferences · idempotent upserts",
    stack: ["Python", "PostgreSQL", "Scraping", "ETL"],
    repo: GH + "/college-baseball-data-pipeline",
    demo: null,
  },
  {
    name: "Polymarket Arbitrage",
    bucket: "D · Quant / Financial",
    desc: "Detects cross-market pricing inefficiencies and computes guaranteed/expected return.",
    metric: "Arbitrage detection · EV calc · P&L log",
    stack: ["JavaScript", "Probability", "HTML/CSS"],
    repo: GH + "/polymarket-arbitrage",
    demo: null,
  },
  {
    name: "Agentic RAG Analyst",
    bucket: "F · Generative AI",
    desc: "Retrieval-augmented LLM assistant answering over a private corpus with inline citations + an eval harness.",
    metric: "Retrieval accuracy [verify] · cited answers",
    stack: ["Python", "LLM", "Vector DB", "RAGAS"],
    repo: GH + "/agentic-rag-analyst",
    demo: null,
    featured: true,
  },
  {
    name: "AI Report Agent",
    bucket: "F · Generative AI",
    desc: "Multi-step LLM agent that auto-generates executive analysis briefs from raw data.",
    metric: "Report time: [verify] hrs → minutes",
    stack: ["Python", "LLM agent", "Tool calling"],
    repo: GH + "/ai-report-agent",
    demo: null,
  },
  {
    name: "Model Serving API",
    bucket: "A · Cloud / Production",
    desc: "Trained model wrapped in a FastAPI service, containerized and deployed to the cloud with monitoring.",
    metric: "Live /predict endpoint · p95 [verify] ms",
    stack: ["Python", "FastAPI", "Docker", "Cloud"],
    repo: GH + "/model-serving-api",
    demo: null,
  },
];
